# Setup
title:               Alan Wang
tagline:             'Someone in CS'
description:         'This <a href="https://www.linkedin.com/in/alan-wang-urd00m/" target="_blank">dudes</a> website. CS @ UIUC'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Alan Wang
  url:               TODO
  email:             alanlw2@illinois.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
paginate_path: "/blog/page:num/"

