# Setup
title:               Alan Wang
tagline:             'Someone in CS'
description:         'This <a href="https://www.linkedin.com/in/alan-wang-urd00m/" target="_blank">dudes</a> website. CS @ UIUC'
url:                 https://urd00m.github.io
baseurl:             ""
# permalink:           pretty

# About/contact
author:
  name:              Alan Wang
  url:               https://urd00m.github.io
  email:             alanlw2@illinois.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-tagging-related_posts

# Custom vars
version:             1.2.0
google_analytics_id: #UA-XXXX-Y

# paginate
paginate:            5
paginate_path: "/blog/page:num/"

# collections
collections:
  General:
    output: true
  Reading:
    output: true
