source "https://rubygems.org"

gem "jekyll"
gem "jekyll-tagging-related_posts"
gem "jekyll-paginate"
gem "jekyll-seo-tag" 
gem "appraisal"
gem "bundler"
gem "minitest-reporters"
gem "minitest"
gem "pry"
gem "rake"
gem "simplecov"